# Generated by Django 4.2.3 on 2023-07-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=None, max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
