# Generated by Django 4.2.3 on 2023-07-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=None, max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
    ]
